<a href="https://colab.research.google.com/github/SnehaPradhan04/Numpy/blob/main/Numpy03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.random.randint(1,10,(4,4))
arr

array([[7, 2, 4, 6],
       [9, 1, 9, 4],
       [8, 3, 2, 7],
       [7, 1, 8, 3]])

In [ ]:
arr.reshape(8,2)

array([[7, 2],
       [4, 6],
       [9, 1],
       [9, 4],
       [8, 3],
       [2, 7],
       [7, 1],
       [8, 3]])

In [ ]:
arr.T

array([[7, 9, 8, 7],
       [2, 1, 3, 1],
       [4, 9, 2, 8],
       [6, 4, 7, 3]])

In [ ]:
arr.flatten()

array([7, 2, 4, 6, 9, 1, 9, 4, 8, 3, 2, 7, 7, 1, 8, 3])

In [ ]:
np.expand_dims(arr, axis=1)

array([[[7, 2, 4, 6]],

       [[9, 1, 9, 4]],

       [[8, 3, 2, 7]],

       [[7, 1, 8, 3]]])

In [ ]:
np.expand_dims(arr, axis=0)

array([[[7, 2, 4, 6],
        [9, 1, 9, 4],
        [8, 3, 2, 7],
        [7, 1, 8, 3]]])

In [ ]:
data = np.array([[1], [2], [3]])
np.squeeze(data)

array([1, 2, 3])

In [ ]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [ ]:
np.repeat(data,5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [ ]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [ ]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [ ]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [ ]:
arr1

array([[6, 3, 7, 5],
       [4, 3, 1, 3],
       [4, 8, 6, 3]])

In [ ]:
arr2

array([[8, 6, 1, 4],
       [2, 6, 3, 7],
       [2, 8, 7, 3]])

In [ ]:
arr1+arr2

array([[14,  9,  8,  9],
       [ 6,  9,  4, 10],
       [ 6, 16, 13,  6]])

In [ ]:
arr1*arr2

array([[48, 18,  7, 20],
       [ 8, 18,  3, 21],
       [ 8, 64, 42,  9]])

In [ ]:
arr1/arr2

array([[0.75      , 0.5       , 7.        , 1.25      ],
       [2.        , 0.5       , 0.33333333, 0.42857143],
       [2.        , 1.        , 0.85714286, 1.        ]])

In [ ]:
arr1-arr2

array([[-2, -3,  6,  1],
       [ 2, -3, -2, -4],
       [ 2,  0, -1,  0]])

In [ ]:
arr1**arr2

array([[ 1679616,      729,        7,      625],
       [      16,      729,        1,     2187],
       [      16, 16777216,   279936,       27]])

In [ ]:
-arr1

array([[-6, -3, -7, -5],
       [-4, -3, -1, -3],
       [-4, -8, -6, -3]])

In [ ]:
arr1>arr2

array([[False, False,  True,  True],
       [ True, False, False, False],
       [ True, False, False, False]])

In [ ]:
arr = np.array(["sneha", "pradhan"])
arr

array(['sneha', 'pradhan'], dtype='<U7')

In [ ]:
np.char.upper(arr)

array(['SNEHA', 'PRADHAN'], dtype='<U7')

In [ ]:
np.char.capitalize(arr)

array(['Sneha', 'Pradhan'], dtype='<U7')

In [ ]:
np.char.title(arr)

array(['Sneha', 'Pradhan'], dtype='<U7')

In [ ]:
arr1

array([[6, 3, 7, 5],
       [4, 3, 1, 3],
       [4, 8, 6, 3]])

In [ ]:
np.sin(arr1)

array([[-0.2794155 ,  0.14112001,  0.6569866 , -0.95892427],
       [-0.7568025 ,  0.14112001,  0.84147098,  0.14112001],
       [-0.7568025 ,  0.98935825, -0.2794155 ,  0.14112001]])

In [ ]:
np.cos(arr1)

array([[ 0.96017029, -0.9899925 ,  0.75390225,  0.28366219],
       [-0.65364362, -0.9899925 ,  0.54030231, -0.9899925 ],
       [-0.65364362, -0.14550003,  0.96017029, -0.9899925 ]])

In [ ]:
np.tan(arr1)

array([[-0.29100619, -0.14254654,  0.87144798, -3.38051501],
       [ 1.15782128, -0.14254654,  1.55740772, -0.14254654],
       [ 1.15782128, -6.79971146, -0.29100619, -0.14254654]])

In [ ]:
np.log10(arr1)

array([[0.77815125, 0.47712125, 0.84509804, 0.69897   ],
       [0.60205999, 0.47712125, 0.        , 0.47712125],
       [0.60205999, 0.90308999, 0.77815125, 0.47712125]])

In [ ]:
np.exp(arr1)

array([[4.03428793e+02, 2.00855369e+01, 1.09663316e+03, 1.48413159e+02],
       [5.45981500e+01, 2.00855369e+01, 2.71828183e+00, 2.00855369e+01],
       [5.45981500e+01, 2.98095799e+03, 4.03428793e+02, 2.00855369e+01]])

In [ ]:
np.power(arr1,3)

array([[216,  27, 343, 125],
       [ 64,  27,   1,  27],
       [ 64, 512, 216,  27]])

In [ ]:
np.mean(arr1)

4.416666666666667

In [ ]:
np.median(arr1)

4.0

In [ ]:
np.std(arr1)

1.9346977943739831

In [ ]:
np.var(arr1)

3.743055555555555

In [ ]:
np.min(arr1)

1

In [ ]:
np.max(arr1)

8

In [ ]:
arr1

array([[6, 3, 7, 5],
       [4, 3, 1, 3],
       [4, 8, 6, 3]])

In [ ]:
arr2

array([[8, 6, 1, 4],
       [2, 6, 3, 7],
       [2, 8, 7, 3]])

In [ ]:
np.subtract(arr1,arr2)

array([[-2, -3,  6,  1],
       [ 2, -3, -2, -4],
       [ 2,  0, -1,  0]])

In [ ]:
arr1-arr2

array([[-2, -3,  6,  1],
       [ 2, -3, -2, -4],
       [ 2,  0, -1,  0]])

In [ ]:
np.multiply(arr1,arr2)

array([[48, 18,  7, 20],
       [ 8, 18,  3, 21],
       [ 8, 64, 42,  9]])

In [ ]:
np.mod(arr1,arr2)

array([[6, 3, 0, 1],
       [0, 3, 1, 3],
       [0, 0, 6, 0]])

In [ ]:
np.power(arr1,arr2)

array([[ 1679616,      729,        7,      625],
       [      16,      729,        1,     2187],
       [      16, 16777216,   279936,       27]])

In [ ]:
np.mean(arr1)

4.416666666666667