<a href="https://colab.research.google.com/github/SnehaPradhan04/Numpy/blob/main/Numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
l = [1,2,3,4,5]
arr = np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [17]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [9]:
arr1 = np.array([[1,2,3] , [2,3,4]])

In [10]:
arr.ndim

1

In [11]:
arr1.ndim

2

In [12]:
arr

array([1, 2, 3, 4, 5])

In [13]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [20]:
mat = np.matrix(l)
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [21]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [22]:
a = arr

In [23]:
arr[0] = 100

In [24]:
arr

array([100,   2,   3,   4,   5])

In [25]:
a

array([100,   2,   3,   4,   5])

In [26]:
b = np.copy(arr)

In [27]:
b

array([100,   2,   3,   4,   5])

In [29]:
b[0] = 234

In [30]:
b

array([234,   2,   3,   4,   5])

In [31]:
arr

array([100,   2,   3,   4,   5])

In [32]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [35]:
iterable = (i*i for i in range(5))

In [36]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [38]:
np.fromstring('23 45 56', sep = ' ')

array([23., 45., 56.])

In [39]:
np.fromstring('23,45,56', sep = ',')

array([23., 45., 56.])

In [40]:
arr.ndim

1

In [41]:
arr1.ndim

2

In [42]:
arr.size

5

In [43]:
arr1.size

6

In [45]:
arr.shape

(5,)

In [46]:
arr1.shape

(2, 3)

In [47]:
arr.dtype

dtype('int64')

In [48]:
arr1.dtype

dtype('int64')