<a href="https://colab.research.google.com/github/SnehaPradhan04/Numpy/blob/main/Numpy02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(np.arange(.4, 5.4, 0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002]

In [6]:
np.linspace(1, 5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [8]:
np.logspace(1, 5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
arr = np.ones((3,4))

In [16]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [17]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [18]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [20]:
arr1 = np.eye(5)

In [22]:
import pandas as pd
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [23]:
np.random.rand(2,3)

array([[0.85191291, 0.34715226, 0.43634913],
       [0.43429786, 0.09139837, 0.74569472]])

In [24]:
np.random.randn(2,3)

array([[-0.62548847,  0.25696458, -0.05510202],
       [-0.84649642, -0.84638192, -0.74586586]])

In [26]:
arr2 = np.random.randint(1, 5, (3,4))

In [27]:
arr2

array([[4, 4, 1, 4],
       [1, 2, 1, 1],
       [1, 1, 2, 1]])

In [28]:
arr2.size

12

In [29]:
arr2.shape

(3, 4)

In [30]:
arr2.reshape(6,2)

array([[4, 4],
       [1, 4],
       [1, 2],
       [1, 1],
       [1, 1],
       [2, 1]])

In [31]:
arr2.reshape(2,6)

array([[4, 4, 1, 4, 1, 2],
       [1, 1, 1, 1, 2, 1]])

In [32]:
arr2.reshape(4,-5)

array([[4, 4, 1],
       [4, 1, 2],
       [1, 1, 1],
       [1, 2, 1]])

In [33]:
arr2.reshape(2,2,3)

array([[[4, 4, 1],
        [4, 1, 2]],

       [[1, 1, 1],
        [1, 2, 1]]])

In [34]:
arr1 = np.random.randint(1, 10, (5,6))

In [35]:
arr1

array([[6, 9, 9, 5, 6, 9],
       [8, 5, 5, 5, 3, 2],
       [8, 9, 7, 8, 7, 9],
       [9, 8, 5, 9, 3, 1],
       [2, 9, 7, 8, 4, 9]])

In [36]:
arr1 > 8

array([[False,  True,  True, False, False,  True],
       [False, False, False, False, False, False],
       [False,  True, False, False, False,  True],
       [ True, False, False,  True, False, False],
       [False,  True, False, False, False,  True]])

In [37]:
arr1[arr1 > 8]

array([9, 9, 9, 9, 9, 9, 9, 9, 9])

In [39]:
arr1[0, [0,1]]

array([6, 9])

In [40]:
arr1[2:4, [2,3]]

array([[7, 8],
       [5, 9]])

In [42]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [43]:
arr1

array([[2, 2, 2],
       [1, 1, 2],
       [1, 2, 1]])

In [44]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [45]:
arr1+arr2

array([[3, 3, 3],
       [2, 3, 3],
       [2, 3, 3]])

In [46]:
arr1-arr2

array([[ 1,  1,  1],
       [ 0, -1,  1],
       [ 0,  1, -1]])

In [47]:
arr1*arr2

array([[2, 2, 2],
       [1, 2, 2],
       [1, 2, 2]])

In [48]:
arr1@arr2

array([[6, 8, 8],
       [4, 5, 6],
       [4, 6, 5]])

In [49]:
arr1/arr2

array([[2. , 2. , 2. ],
       [1. , 0.5, 2. ],
       [1. , 2. , 0.5]])

In [50]:
arr1/0

<ipython-input-50-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [51]:
#numpy broadcasting
arr = np.zeros((3,4))

In [52]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
arr+7

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [54]:
a = np.array([1,2,3,4])
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [57]:
b = np.array([[3,4,5]])
arr1 = arr+b.T

In [56]:
b.T

array([[3],
       [4],
       [5]])

In [58]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [59]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [60]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [61]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [65]:
np.min(arr1)

3.0

In [64]:
np.max(arr1)

5.0